### ISSUE TITLE
TypeError: require is not a function with Webpack

### ISSUE THREAD

**Issue by LarenDorr** [LarenDorr/igetter#1]
Use webpack bundle code will throw error :
```js
webpack:///./node_modules/formidable/lib/incoming_form.js?:3
var crypto = require('crypto');
             ^
TypeError: require is not a function
    at eval (webpack:///./node_modules/formidable/lib/incoming_form.js?:3:14)
    at Object../node_modules/formidable/lib/incoming_form.js (C:\WorkSpace\Test\igetter-test\dist\index.js:882:1)
    at __webpack_require__ (C:\WorkSpace\Test\igetter-test\dist\index.js:20:30)
    at eval (webpack:///./node_modules/formidable/lib/index.js?:1:20)
    at Object../node_modules/formidable/lib/index.js (C:\WorkSpace\Test\igetter-test\dist\index.js:893:1)
    at __webpack_require__ (C:\WorkSpace\Test\igetter-test\dist\index.js:20:30)
    at eval (webpack:///./node_modules/superagent/lib/node/index.js?:34:18)
    at Object../node_modules/superagent/lib/node/index.js (C:\WorkSpace\Test\igetter-test\dist\index.js:5068:1)
    at __webpack_require__ (C:\WorkSpace\Test\igetter-test\dist\index.js:20:30)
    at eval (webpack:///./node_modules/@igetter/core/dist/index.js?:1:339)
```

**Comment by LarenDorr** [comment]
Because dependency superagent use node-formidable, it has an issue [https://github.com/felixge/node-formidable/issues/337](url). 
resolve:  add it to webpack config
```js
plugins: [
    new webpack.DefinePlugin({
      "global.GENTLY": false
    })
  ]
```

**Comment by LarenDorr** [comment]
Consider replace Downloader lib.
